/* Writes work/ui/lucide.js: only the Lucide icons the project pages use, as SVG strings.
   The ULS and ICCC prototypes were built with Lucide (Figma Make / shadcn exports), so these
   are the products' own icons. Pulling the ~30 needed out of the 358KB bundle keeps the page light.
   Run:  node tools/lucide_subset.js <path to lucide.min.js 0.469.0> */
const fs = require('fs');
const path = require('path');
const lucide = require(path.resolve(process.argv[2]));
const names = ['layout-grid','users','user','calendar','clipboard-list','map-pin','wallet','file-text','credit-card',
  'chart-column','message-square','circle-help','settings','search','download','bell','circle-check','indian-rupee',
  'trending-up','trending-down','plus','filter','arrow-right','chevron-up','chevron-down','clock','circle-alert',
  'camera','droplets','lightbulb','wind','wifi','zap','x','minus','maximize-2','triangle-alert','circle-check-big',
  'user-plus','refresh-cw','map','layout-dashboard','ticket','message-square-text','file-text','move','star','shield','cpu','building-2','panel-right-open','menu','crown','pencil','undo-2','redo-2','message-circle','presentation','share','panel-left','shapes','type','briefcase','cloud-upload','pen-tool','folder','blocks','image-plus','chart-no-axes-column','notebook-pen','square-play','timer','layout-panel-top','grid-2x2','send-horizontal','sparkles','upload','cloud'];
const pascal = n => n.split('-').map(s => s[0].toUpperCase() + s.slice(1)).join('');
const out = {};
for (const n of names) {
  const node = lucide.icons[pascal(n)];
  if (!node) { console.error('missing', n); continue; }
  const kids = (Array.isArray(node[2]) ? node[2] : node).map(([tag, attrs]) =>
    '<' + tag + Object.entries(attrs).filter(([k]) => k !== 'key').map(([k, v]) => ` ${k}="${v}"`).join('') + '/>').join('');
  out[n] = kids;
}
const js = '/* generated by tools/lucide_subset.js from lucide 0.469.0 (ISC). <i data-lucide="name"> becomes the icon. */\n' +
  '(function(){var I=' + JSON.stringify(out) + ';\n' +
  'window.LUCIDE=function(root,sw){[].forEach.call((root||document).querySelectorAll("i[data-lucide]"),function(el){' +
  'var n=el.getAttribute("data-lucide");if(!I[n])return;var s=document.createElementNS("http://www.w3.org/2000/svg","svg");' +
  's.setAttribute("viewBox","0 0 24 24");s.setAttribute("fill","none");s.setAttribute("stroke","currentColor");' +
  's.setAttribute("stroke-width",el.getAttribute("data-sw")||sw||2);s.setAttribute("stroke-linecap","round");s.setAttribute("stroke-linejoin","round");' +
  's.setAttribute("aria-hidden","true");s.setAttribute("class","lc "+(el.className||""));if(el.getAttribute("style"))s.setAttribute("style",el.getAttribute("style"));s.innerHTML=I[n];el.parentNode.replaceChild(s,el);});};})();\n';
fs.writeFileSync(path.join(__dirname, '..', 'work', 'ui', 'lucide.js'), js);
console.log('wrote work/ui/lucide.js', js.length, 'bytes,', Object.keys(out).length, 'icons');
